
source "qemu" "autogenerated_1" {
  accelerator          = "kvm"
  boot_wait            = "10s"
  communicator         = "ssh"
  cpus                 = "${var.cpus}"
  disk_compression     = true
  disk_discard         = "unmap"
  disk_image           = true
  disk_interface       = "virtio"
  disk_size            = "${var.disk_size}"
  format               = "qcow2"
  headless             = "${var.headless}"
  iso_url              = "${local.v.iso_url}"
  iso_checksum         = "${local.v.iso_checksum}"
  iso_target_extension = "qcow2"
  memory               = "${var.memory}"
  net_device           = "virtio-net"
  output_directory     = "${local.v.output_directory}"
  shutdown_command     = "sudo systemctl poweroff"
  ssh_password         = "provision"
  ssh_timeout          = "30m"
  ssh_username         = "provision"
  vm_name              = "${var.distribution}.qcow2"
}

build {
  sources = ["source.qemu.autogenerated_1"]

  provisioner "shell" {
    execute_command = "sudo bash -c '{{ .Path }}'"
    pause_before    = "15s"
    scripts         = ["scripts/network_wait.sh", "scripts/${local.os_name}/install_cloud_init.sh", "scripts/configure_cloud_init.sh", "scripts/${local.os_name}/cleanup.sh", "scripts/cleanup_host.sh", "scripts/cleanup_logs.sh", "scripts/minimize.sh"]
  }

  post-processor "checksum" {
    checksum_types = ["sha256"]
    output = "${local.v.output_directory}/${var.distribution}.sha256"
    keep_input_artifact = true
  }
}

locals {
  v = {
    output_directory = "${var.build_directory}/cloud/"
    iso_url = var.iso_url != "" ? var.iso_url : "${var.build_directory}/${local.os_name}/${var.distribution}.qcow2"
    iso_checksum = var.iso_checksum != "" ? var.iso_checksum : "file:${var.build_directory}/${local.os_name}/${var.distribution}.sha256"
  }
}

variable "disk_size" {
  type = string
  default = "4G"
}
