source "qemu" "autogenerated_1" {
  accelerator          = "kvm"
  boot_wait            = "10s"
  communicator         = "ssh"
  cpus                 = "${var.cpus}"
  disk_compression     = true
  disk_discard         = "unmap"
  disk_image           = true
  disk_interface       = "virtio"
  disk_size            = "${var.disk_size}"
  format               = "qcow2"
  headless             = "${var.headless}"
  iso_url              = "${local.iso_url}"
  iso_checksum         = "${local.iso_checksum}"
  iso_target_extension = "qcow2"
  memory               = "${var.memory}"
  net_device           = "virtio-net"
  output_directory     = "${local.v.output_directory}"
  shutdown_command     = "sudo systemctl poweroff"
  ssh_password         = "provision"
  ssh_timeout          = "30m"
  ssh_username         = "provision"
  vm_name              = "${var.distribution}.qcow2"
}

build {
  sources = ["source.qemu.autogenerated_1"]

  provisioner "shell" {
    environment_vars = ["DEV_DISK=/dev/vda", "DEV_PARTITION_NR=3"]
    execute_command  = "{{ .Vars }} sudo -E -S bash -c '{{ .Path }}'"
    only             = ["qemu.autogenerated_1"]
    scripts          = ["scripts/disk_resize.sh"]
  }

  provisioner "shell" {
    inline         = ["cat /etc/fstab", "sudo lvresize -r -l +50%FREE vg_host/lv_var", "sudo lvresize -r -l +100%FREE vg_host/lv_root"]
    inline_shebang = "/bin/bash -ex"
    only             = ["qemu.autogenerated_1"]
  }

  provisioner "shell" {
    execute_command = "{{ .Vars }} sudo -E -S bash -c '{{ .Path }}'"
    scripts         = ["scripts/network_wait.sh", "scripts/setup_kitchen.sh", "scripts/${local.os_name}/install_kitchen_requirements.sh", "scripts/${local.os_name}/cleanup.sh", "scripts/cleanup_host.sh", "scripts/cleanup_logs.sh", "scripts/minimize.sh"]
  }

  post-processor "checksum" {
    checksum_types = ["sha256"]
    output = "${local.v.output_directory}/${var.distribution}.sha256"
    keep_input_artifact = true
  }
}

locals {
  v = {
    output_directory = "${var.build_directory}/kitchen/"
  }
}


variable "disk_size" {
  type = string
  default = "10G"
}
