variable "iso_url" {
  type = string
  default = ""
}

variable "iso_checksum" {
  type = string
  default = ""
}

variable "distribution" {
  type    = string
}

variable "enable_pki_install" {
  type    = bool
  default = false
}

variable "build_directory" {
  type    = string
  default = "output"
}

variable "vault_addr" {
  type    = string
  default = ""
}

variable "vault_pki_secrets_path" {
  type    = string
  default = "pki"
}

variable "cpus" {
  type    = number
  default = 2
}

variable "memory" {
  type    = number
  description = "in megabytes"
  default = 1024
}

variable "headless" {
  type    = bool
  default = true
}

variable "https_proxy" {
  type    = string
  default = ""
}

variable "http_proxy" {
  type    = string
  default = ""
}

variable "no_proxy" {
  type    = string
  default = ""
}

locals {
  os_name = split("-", var.distribution)[0]
  boot_command = local.v.boot_command != null ? local.v.boot_command : []
}


source "qemu" "autogenerated_1" {
  accelerator      = "kvm"
  boot_command     = local.boot_command
  boot_wait        = "1s"
  cpus             = "${var.cpus}"
  disk_compression = true
  disk_discard     = "unmap"
  disk_image       = false
  disk_interface   = "virtio"
  disk_size        = "${var.disk_size}"
  format           = "qcow2"
  headless         = "${var.headless}"
  http_directory   = "srv"
  iso_url          = "${var.iso_url}"
  iso_checksum     = "${var.iso_checksum}"
  // iso_url          = "${var.mirror}/${var.mirror_directory}/${var.distribution}.iso"
  //iso_checksum     = "file:${var.mirror}/${var.mirror_directory}/sha256sums.txt"
  memory           = "${var.memory}"
  net_device       = "virtio-net"
  output_directory = "${local.v.output_directory}"
  shutdown_command = "sudo systemctl poweroff"
  ssh_password     = "provision"
  ssh_timeout      = "30m"
  ssh_username     = "provision"
  vm_name          = "${var.distribution}.qcow2"
}
