
source "qemu" "autogenerated_1" {
  accelerator          = "kvm"
  boot_wait            = "10s"
  communicator         = "ssh"
  cpus                 = "${var.cpus}"
  disk_compression     = true
  disk_discard         = "unmap"
  disk_image           = true
  disk_interface       = "virtio"
  disk_size            = "${var.disk_size}"
  format               = "qcow2"
  headless             = "${var.headless}"
  iso_url              = "${local.v.iso_url}"
  iso_checksum         = "${local.v.iso_checksum}"
  iso_target_extension = "qcow2"
  memory               = "${var.memory}"
  net_device           = "virtio-net"
  output_directory     = "${local.output_directory}"
  shutdown_command     = "sudo systemctl poweroff"
  ssh_password         = "provision"
  ssh_timeout          = "30m"
  ssh_username         = "provision"
  vm_name              = "${var.distribution}.qcow2"
}

build {
  sources = ["source.qemu.autogenerated_1"]

  provisioner "shell" {
    environment_vars = ["DEV_DISK=/dev/vda", "DEV_PARTITION_NR=3"]
    execute_command  = "{{ .Vars }} sudo -E -S bash -c '{{ .Path }}'"
    scripts          = ["scripts/disk_resize.sh"]
  }

  provisioner "shell" {
    inline         = ["sudo lvresize -r -l +100%FREE vg_host/lv_var"]
    inline_shebang = "/bin/bash -ex"
  }

  provisioner "shell" {
    execute_command = "sudo bash -c '{{ .Path }}'"
    scripts         = ["scripts/network_wait.sh", "scripts/add_root_keys.sh", "scripts/${local.os_name}/setup_ansible.sh"]
  }

  provisioner "ansible" {
    extra_arguments = ["--become", "--extra-vars", "ansible_remote_tmp=/tmp/ansible"]
    playbook_file   = "./kubernetes/playbook_kubernetes.yml"
    user            = "provision"
  }

  provisioner "shell" {
    execute_command = "sudo bash -c '{{ .Path }}'"
    scripts         = ["scripts/${local.os_name}/cleanup.sh", "scripts/cleanup_host.sh", "scripts/cleanup_logs.sh", "scripts/minimize.sh"]
  }

  post-processor "checksum" {
    checksum_types = ["sha256"]
    output = "${local.output_directory}/${var.distribution}.sha256"
    keep_input_artifact = true
  }
}

locals {
  v = {
    build_type = "kubernetes"
    iso_url = var.iso_url != "" ? var.iso_url : "${var.build_directory}/${local.os_name}/${var.distribution}.qcow2"
    iso_checksum = var.iso_checksum != "" ? var.iso_checksum : "file:${var.build_directory}/${local.os_name}/${var.distribution}.sha256"
  }
}

variable "disk_size" {
  type = string
  default = "10G"
}
