
source "qemu" "autogenerated_1" {
  accelerator          = "kvm"
  boot_wait            = "10s"
  communicator         = "ssh"
  cpus                 = "${var.cpus}"
  disk_compression     = true
  disk_discard         = "unmap"
  disk_image           = true
  disk_interface       = "virtio"
  disk_size            = "${var.disk_size}"
  format               = "qcow2"
  headless             = "${var.headless}"
  iso_url              = "${local.v.iso_url}"
  iso_checksum         = "${local.v.iso_checksum}"
  iso_target_extension = "qcow2"
  memory               = "${var.memory}"
  net_device           = "virtio-net"
  output_directory     = "${local.v.output_directory}"
  vm_name              = "${var.distribution}.qcow2"
  shutdown_command     = "sudo systemctl poweroff"
  ssh_username         = "provision"
  ssh_password         = "provision"
  ssh_timeout          = "30m"
}


build {
  sources = ["source.qemu.autogenerated_1"]

  provisioner "shell" {
    environment_vars = ["DEV_DISK=/dev/vda", "DEV_PARTITION_NR=3"]
    execute_command  = "{{ .Vars }} sudo -E -S bash -c '{{ .Path }}'"
    only             = ["qemu"]
    scripts          = ["scripts/disk_resize.sh"]
  }

  provisioner "shell" {
    inline         = ["sudo lvresize -r -l +70%FREE vg_host/lv_var", "sudo lvresize -r -l +100%FREE vg_host/lv_root"]
    inline_shebang = "/bin/bash -ex"
    only           = ["qemu"]
  }

  provisioner "shell" {
    environment_vars = ["SALT_VERSION_TAG=${var.salt_version_tag}", "SALT_GIT_URL=${var.salt_git_url}", "http_proxy=${var.http_proxy}", "https_proxy=${var.https_proxy}", "no_proxy=${var.no_proxy}"]
    execute_command  = "{{ .Vars }} sudo -E -S bash -c '{{ .Path }}'"
    scripts          = ["scripts/network_wait.sh", "scripts/${local.os_name}/install_salt.sh", "scripts/install_salt.sh", "scripts/${local.os_name}/cleanup.sh", "scripts/cleanup_host.sh", "scripts/cleanup_logs.sh", "scripts/minimize.sh"]
  }

  post-processor "checksum" {
    checksum_types = ["sha256"]
    output = "${local.v.output_directory}/${var.distribution}.sha256"
    keep_input_artifact = true
  }

  post-processor "shell-local" {
    inline = ["set -eux", "scripts/qemu/convert_raw.sh \"${local.v.output_directory}\" \"${var.distribution}\""]
    only   = ["qemu.autogenerated_1"]
  }
}


locals {
  v = {
    output_directory = "${var.build_directory}/salt/${var.parent_image_type}"
    iso_url = var.iso_url != "" ? var.iso_url : "${var.build_directory}/${var.parent_image_type}/${var.distribution}.qcow2"
    iso_checksum = var.iso_checksum != "" ? var.iso_checksum : "file:${var.build_directory}/${var.parent_image_type}/${var.distribution}.sha256"
  }
}


variable "disk_size" {
  type = string
  default = "10G"
}


variable "salt_version_tag" {
  type = string
  default = "v3004.2"
}


variable "salt_git_url" {
  type = string
  default = "https://github.com/saltstack/salt"
}


variable "parent_image_type" {
  type        = string
  description = "which image this build is based upon from the default build_directory, use iso_url and iso_checksum otherwise"
  validation {
    condition     = contains(["cloud", "kitchen", "debian"] , var.parent_image_type)
    error_message = "Variable parent_image_type can only be one of: cloud, kitchen, debian."
  }
}
